/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistaGUI;

/**
 *
 * @author Usuario
 */
import Excepciones.CadenaAlphaException;
import controlador.ConexionBD;
import controlador.ControladorUsuarios;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Usuarios;

public class GUIUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form GUIUsuarios
     */
    ControladorUsuarios contusuario;
    Object[] datos;
    DefaultTableModel model;
    ConexionBD conn;
    Connection con;
    Usuarios usug;

    public GUIUsuarios() {
        initComponents();
        contusuario = new ControladorUsuarios();
        conn = new ConexionBD(); // separo memoria
        con = conn.conexionDB(); // invoco el metodo
        datos = new Object[10];
        model = (DefaultTableModel) jTable1.getModel();
        insertarDatosDefecto();
        usug = new Usuarios();
    }

    private void insertarDatosDefecto() {

//        Usuarios usuar = new Usuarios(1076432789, "Tarjeta de identidad", "Raul", "Ramirez", "Calle 7 #2-23", 8996543, "RamirezRau@Gmail.com", "10/07/2022");
//        contusuario.insertar(usuar);
//        usuar = new Usuarios (34065778, "Cedula de ciudadania", "Maria", "Perez", "Calle 2 #5-81", 8936745, "PerezMaria@Gmail.com", "02/09/2003");
//        contusuario.insertar(usuar);
//         usuar = new Usuarios (1056139876,"Tarjeta de identidad", "Camilo", "Palacio", "Cll 6 #8-46", 8906712, "PalacioCamilo@Gmail.com", "07/22/2004");
//        contusuario.insertar(usuar);
        String query = "SELECT * FROM usuario ORDER BY cedula";
        Statement st;
        Usuarios usu;
        try {
            st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
                usu = new Usuarios();
                usu.setCedula(rs.getDouble("cedula"));
                usu.setTipo(rs.getString("tipo"));
                usu.setNombre(rs.getString("nombre"));
                usu.setApellido(rs.getString("apellido"));
                usu.setDireccion(rs.getString("direccion"));
                usu.setTelefono(rs.getDouble("telefono"));
                usu.setCorreo(rs.getString("correo"));
                usu.setFecha(rs.getString("fecha"));
                usu.setNickname(rs.getString("usuario"));
                usu.setContrasena(rs.getString("contrasena"));

                contusuario.insertar(usu);
            }
        } catch (SQLException ex) {
            Logger.getLogger(GUIUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }

        for (Usuarios auto1 : contusuario.arreglousu) {
            datos[0] = auto1.getCedula();
            datos[1] = auto1.getTipo();
            datos[2] = auto1.getNombre();
            datos[3] = auto1.getApellido();
            datos[4] = auto1.getDireccion();
            datos[5] = auto1.getTelefono();
            datos[6] = auto1.getCorreo();
            datos[7] = auto1.getFecha();
            datos[8] = auto1.getNickname();
            datos[9] = auto1.getContrasena();

            model.addRow(datos);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jTextFieldApellido = new javax.swing.JTextField();
        jTextFieldCorreo = new javax.swing.JTextField();
        jTextFieldTipo = new javax.swing.JTextField();
        jTextFieldDireccion = new javax.swing.JTextField();
        jTextFieldFecha = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldTelefono = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonInsertar = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jButtonOrdenar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldContrasena = new javax.swing.JTextField();
        jTextFieldUsuario = new javax.swing.JTextField();
        jLabelUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("Usuarios");

        jLabel2.setText("ID");

        jLabel3.setText("Tipo");

        jLabel4.setText("Nombre");

        jLabel5.setText("Apellido");

        jLabel6.setText("Direccion");

        jLabel7.setText("Telefono");

        jLabel8.setText("Correo");

        jLabel9.setText("Fecha de Nacimiento");

        jTextFieldID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldIDFocusLost(evt);
            }
        });
        jTextFieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDActionPerformed(evt);
            }
        });

        jTextFieldNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNombreFocusLost(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tipo", "Nombre", "Apellido", "Direccion", "Telefono", "Correo", "Fecha", "Usuario", "Contraseña"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(7).setResizable(false);
            jTable1.getColumnModel().getColumn(8).setResizable(false);
            jTable1.getColumnModel().getColumn(9).setResizable(false);
        }

        jButtonInsertar.setText("Insertar");
        jButtonInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarActionPerformed(evt);
            }
        });

        jButtonBorrar.setText("Borrar");
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });

        jButtonOrdenar.setText("Ordenar");
        jButtonOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarActionPerformed(evt);
            }
        });

        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jLabel11.setText("Contraseña");

        jLabelUsuario.setText("Usuario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelUsuario)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldID)
                                .addComponent(jTextFieldTipo)
                                .addComponent(jTextFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(jButtonInsertar)
                                        .addGap(67, 67, 67)
                                        .addComponent(jButtonBorrar)
                                        .addGap(52, 52, 52)
                                        .addComponent(jButtonModificar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(123, 123, 123)
                                        .addComponent(jLabel1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(54, 54, 54)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel5)
                                                    .addGap(27, 27, 27))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel11)
                                                        .addComponent(jLabel6))
                                                    .addGap(18, 18, 18)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(38, 38, 38)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jButtonOrdenar)
                                    .addComponent(jLabel9))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonModificar)
                            .addComponent(jButtonOrdenar)
                            .addComponent(jButtonBorrar)
                            .addComponent(jButtonInsertar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelUsuario)))
                .addContainerGap(298, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarActionPerformed
        // TODO add your handling code here:
        Usuarios usu = new Usuarios();
        usu.setCedula(Integer.parseInt(jTextFieldID.getText()));
        usu.setTipo(jTextFieldTipo.getText());
        usu.setNombre(jTextFieldNombre.getText());
        usu.setApellido(jTextFieldApellido.getText());
        usu.setDireccion(jTextFieldDireccion.getText());
        usu.setTelefono(Integer.parseInt(jTextFieldTelefono.getText()));
        usu.setCorreo(jTextFieldCorreo.getText());
        usu.setFecha(jTextFieldFecha.getText());
        usu.setNickname(jTextFieldUsuario.getText());
        usu.setContrasena(jTextFieldContrasena.getText());

        if (contusuario.insertar(usu)) {
            insertarBD(usu);
            datos[0] = usu.getCedula();
            datos[1] = usu.getTipo();
            datos[2] = usu.getNombre();
            datos[3] = usu.getApellido();
            datos[4] = usu.getDireccion();
            datos[5] = usu.getTelefono();
            datos[6] = usu.getCorreo();
            datos[7] = usu.getFecha();
            datos[8] = usu.getNickname();
            datos[9] = usu.getContrasena();
            model.addRow(datos);
            JOptionPane.showMessageDialog(this, "Usuario insertado");
        } else {
            JOptionPane.showMessageDialog(this, "Error al insertar ");
        }
    }//GEN-LAST:event_jButtonInsertarActionPerformed

    private void jButtonOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarActionPerformed
        // TODO add your handling code here:
        contusuario.ordenar();
        int n = model.getRowCount();
        for (int i = 0; i < n; i++) {
            model.removeRow(0);
        }
        for (Usuarios usu : contusuario.arreglousu) {
            datos[0] = usu.getCedula();
            datos[1] = usu.getTipo();
            datos[2] = usu.getNombre();
            datos[3] = usu.getApellido();
            datos[4] = usu.getDireccion();
            datos[5] = usu.getTelefono();
            datos[6] = usu.getCorreo();
            datos[7] = usu.getFecha();
            datos[8] = usu.getNickname();
            datos[9] = usu.getContrasena();
            model.addRow(datos);

        }
    }//GEN-LAST:event_jButtonOrdenarActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        // TODO add your handling code here:
        int pos = jTable1.getSelectedRow();
        Usuarios usu = new Usuarios();
        usu = contusuario.arreglousu.get(pos);
        usu.setCedula(Integer.parseInt(jTextFieldID.getText()));
        usu.setTipo(jTextFieldTipo.getText());
        usu.setNombre(jTextFieldNombre.getText());
        usu.setApellido(jTextFieldApellido.getText());
        usu.setDireccion(jTextFieldDireccion.getText());
        usu.setTelefono(Integer.parseInt(jTextFieldTelefono.getText()));
        usu.setCorreo(jTextFieldCorreo.getText());
        usu.setFecha(jTextFieldFecha.getText());
        usu.setNickname(jTextFieldUsuario.getText());
        usu.setContrasena(jTextFieldContrasena.getText());

        usu = (Usuarios) contusuario.modificar(usu);

        int n = model.getRowCount();
        for (int i = 0; i < n; i++) {
            model.removeRow(0);
        }
        for (Usuarios auto1 : contusuario.arreglousu) {
            datos[0] = auto1.getCedula();
            datos[1] = auto1.getTipo();
            datos[2] = auto1.getNombre();
            datos[3] = auto1.getApellido();
            datos[4] = auto1.getDireccion();
            datos[5] = auto1.getTelefono();
            datos[6] = auto1.getCorreo();
            datos[7] = auto1.getFecha();
            datos[8] = auto1.getNickname();
            datos[9] = auto1.getContrasena();

            model.addRow(datos);

        }
        JOptionPane.showMessageDialog(this, "Usuario Modificado");
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int seleccion = jTable1.getSelectedRow();
        jTextFieldID.setText(jTable1.getValueAt(seleccion, 0).toString());
        jTextFieldTipo.setText(jTable1.getValueAt(seleccion, 1).toString());
        jTextFieldNombre.setText(jTable1.getValueAt(seleccion, 2).toString());
        jTextFieldApellido.setText(jTable1.getValueAt(seleccion, 3).toString());
        jTextFieldDireccion.setText(jTable1.getValueAt(seleccion, 4).toString());
        jTextFieldTelefono.setText(jTable1.getValueAt(seleccion, 5).toString());
        jTextFieldCorreo.setText(jTable1.getValueAt(seleccion, 6).toString());
        jTextFieldFecha.setText(jTable1.getValueAt(seleccion, 7).toString());
        jTextFieldUsuario.setText(jTable1.getValueAt(seleccion, 8).toString());
        jTextFieldContrasena.setText(jTable1.getValueAt(seleccion, 9).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        // TODO add your handling code here:
        int pos = jTable1.getSelectedRow();

        Usuarios usu = new Usuarios();
        usu = contusuario.arreglousu.get(pos);
        JOptionPane.showMessageDialog(null, "Entre a borrar el objeto " + pos + " " + usu.getCedula());

        if (contusuario.borrar(usu)) {
            model.removeRow(pos);
            borrarBD(usu);
            JOptionPane.showMessageDialog(null, "Objeto Borrado");
        } else
            JOptionPane.showMessageDialog(null, "No se pudo borrar el objeto");
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    private void jTextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDActionPerformed

    private void jTextFieldIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldIDFocusLost
        // TODO add your handling code here:
//        try
//        {
//          usug.setCedula(Double.parseDouble(jTextFieldID.getText()));
//        }
//        catch(NumberFormatException ex)
//        {
//          JOptionPane.showMessageDialog(this, ex);
//          jTextFieldID.setText("");
//          jTextFieldID.requestFocus();
//        }
    }//GEN-LAST:event_jTextFieldIDFocusLost

    private void jTextFieldNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNombreFocusLost
        // TODO add your handling code here:
//        CadenaAlphaException cadena = new CadenaAlphaException();
//        try {
//            cadena.validarCadena(jTextFieldNombre.getText());
//        } catch (CadenaAlphaException ex) {
//            JOptionPane.showMessageDialog(this, ex.getMessage());
//            jTextFieldNombre.setText("");
//            jTextFieldNombre.requestFocus();
//        }

    }//GEN-LAST:event_jTextFieldNombreFocusLost
    private void insertarBD(Usuarios usu) {
        String query = "INSERT INTO concesionario.usuario VALUES("+
                 usu.getCedula() + ",'"+  usu.getTipo() + "','" + usu.getNombre() + "','"
                + usu.getApellido() + "','" + usu.getDireccion() + "',"
                + usu.getTelefono() + ",'" + usu.getCorreo() + "','" + usu.getFecha() + "','" + usu.getNickname() + "','" + usu.getContrasena() + "')";
        System.out.println(query);

        try {
            Statement st = con.createStatement();
            st.executeUpdate(query);
            JOptionPane.showMessageDialog(this, "Insertado BD");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "NO Insertado BD");
            ex.printStackTrace();
        }

    }

    private void borrarBD(Usuarios usu) {
        String query = "DELETE FROM concesionario.usuario where usuario.cedula='" + usu.getCedula() + "'";
        System.out.println(query);
        try {
            Statement st = con.createStatement();
            st.executeUpdate(query);
            JOptionPane.showMessageDialog(this, "Usuario eliminado BD");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Usuario NO eliminado BD");
            Logger.getLogger(GUIUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GUIUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GUIUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GUIUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GUIUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GUIUsuarios().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonInsertar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonOrdenar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldContrasena;
    private javax.swing.JTextField jTextFieldCorreo;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldFecha;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelefono;
    private javax.swing.JTextField jTextFieldTipo;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
