/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistaGUI;

/**
 *
 * @author Usuario
 */
import controlador.ControladorUsuarios;
import modelo.Usuarios;
import javax.swing.JOptionPane;
public class PrincipalGUI extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalGUI
     */
    controlador.ControladorUsuarios contusuar;
    public PrincipalGUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        contusuar=new ControladorUsuarios();
        insertarDatosDefecto();
    }
    private void insertarDatosDefecto(){
   
        Usuarios usuar = new Usuarios(10764897, "Tarjeta de identidad", "Raul", "Ramirez", "Calle 7 #2-23", 8996543, "RamirezRau@Gmail.com", "10/07/2004");
        usuar.setNickname("raulra");
        usuar.setContrasena("raul123");
        usuar.setTipo("Administrador");
        contusuar.insertar(usuar);
        
//        usuar = new Usuarios (34065778, "Cedula de ciudadania", "Maria", "Perez", "Calle 2 #5-81", 8936745, "PerezMaria@Gmail.com", "02/09");
//        usuar.setNickname("MariaPerez");
//        usuar.setContrasena("Maria123");
//        usuar.setTipo("Cliente");
//        contusuar.insertar(usuar);
//        
//        usuar = new Usuarios (1056139876,"Tarjeta de identidad", "Camilo", "Palacio", "Cll 6 #8-46", 8906712, "PalacioCamilo@Gmail.com", "07/22");
//        usuar.setNickname("CamiloPa");
//        usuar.setContrasena("Palacio123");
//        usuar.setTipo("Vendedor");
//        contusuar.insertar(usuar);
//        
//        contusuar.insertar(usuar);
//        Usuarios usu=new Usuarios();
//        usu.setNickname("root");
//        usu.setContrasena("Paswoord");
//        usu.setTipo("Vendedor");
//        usu.setCedula(000);
//        contusuar.insertar(usu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSalir = new javax.swing.JButton();
        jLabelIcono = new javax.swing.JLabel();
        jComboBoxRol = new javax.swing.JComboBox<>();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelContrasena = new javax.swing.JLabel();
        jPasswordFieldContrasena = new javax.swing.JPasswordField();
        BotonIniciar = new javax.swing.JButton();
        jTextFieldNickname = new javax.swing.JTextField();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSalir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(0, 0, 51));
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        jLabelIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2022-10-16_20h21_28-removebg-preview.png"))); // NOI18N
        getContentPane().add(jLabelIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 160, 230));

        jComboBoxRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Administrador", "Vendedor", "Cliente" }));
        getContentPane().add(jComboBoxRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 170, -1));

        jLabelUsuario.setBackground(new java.awt.Color(255, 255, 255));
        jLabelUsuario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsuario.setText("Usuario");
        getContentPane().add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        jLabelContrasena.setBackground(new java.awt.Color(255, 255, 255));
        jLabelContrasena.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelContrasena.setForeground(new java.awt.Color(255, 255, 255));
        jLabelContrasena.setText("Contraseña");
        getContentPane().add(jLabelContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, -1));

        jPasswordFieldContrasena.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        getContentPane().add(jPasswordFieldContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 180, -1));

        BotonIniciar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BotonIniciar.setForeground(new java.awt.Color(0, 0, 51));
        BotonIniciar.setText("Iniciar Sesión");
        BotonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIniciarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, -1, -1));
        getContentPane().add(jTextFieldNickname, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 180, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PrincipalGUI.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void BotonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIniciarActionPerformed
        // TODO add your handling code here:
        boolean acceso=false;
        String password = new String(jPasswordFieldContrasena.getPassword());
        String tipoUsu = (String)jComboBoxRol.getSelectedItem();
        for(Usuarios usu: contusuar.arreglousu)
        {
           int res1= password.compareTo(usu.getContrasena());
           int res2= usu.getNickname().compareTo(jTextFieldNickname.getText());
           
           System.out.println("res1="+ res1 + "res2"+ res2);
           if(res1==0 && res2==0 && usu.getTipo().compareTo(tipoUsu)==0)  
           {
             acceso=true;
             break;
           }  
        }
        if(acceso && tipoUsu.compareTo("Administrador")==0)
        {
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdministrador().setVisible(true);
            }
        }
        );
          
        }
        else if(acceso && tipoUsu.compareTo("Cliente")==0)
        {
            GUIAutomovil car=new GUIAutomovil();
            car.getjBOrdenarPlaca().setEnabled(false);
          java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCliente().setVisible(true);
            }
        }
        );
            
        }
        else if(acceso && tipoUsu.compareTo("Vendedor")==0)
        {
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuVendedor().setVisible(true);
            }
        }
        );
          
        }
        else     
        {
          JOptionPane.showMessageDialog(this, "Usuario o contrasea incorrecta"); 
          jPasswordFieldContrasena.setText("");
          jTextFieldNickname.setText("");
        }
        
       
        
           
    }//GEN-LAST:event_BotonIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonIniciar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JComboBox<String> jComboBoxRol;
    private javax.swing.JLabel jLabelContrasena;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelIcono;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPasswordField jPasswordFieldContrasena;
    private javax.swing.JTextField jTextFieldNickname;
    // End of variables declaration//GEN-END:variables
}
